// Compromise Option Display - Shows AI-generated compromise when parties disagree
'use client';

import React, { useState } from 'react';
import { 
  Scale, 
  CheckCircle, 
  XCircle, 
  AlertCircle, 
  TrendingUp,
  Calendar,
  Users,
  Lightbulb
} from 'lucide-react';
import { apiRequest } from '@/lib/api';

interface SettlementOption {
  optionId: string;
  optionName: string;
  optionType: 'conservative' | 'balanced' | 'progressive' | 'compromise';
  proposedResolution: string;
  fairnessScore: number;
  legalBasis: string;
  prosForComplainant: string[];
  consForComplainant: string[];
  prosForRespondent: string[];
  consForRespondent: string[];
  implementationSteps: string[];
  timelineDays: number;
  isCompromise: boolean;
  generatedAt: string;
}

interface PartySelection {
  partyType: 'complainant' | 'respondent';
  selectedOptionId: string;
  selectedOptionName: string;
  comments?: string;
  selectedAt: string;
}

interface CompromiseOptionProps {
  caseId: string;
  compromiseOption: SettlementOption;
  complainantSelection: PartySelection;
  respondentSelection: PartySelection;
  currentUserPartyType: 'complainant' | 'respondent';
  onAccept: () => void;
  onReject: () => void;
}

export default function CompromiseOption({
  caseId,
  compromiseOption,
  complainantSelection,
  respondentSelection,
  currentUserPartyType,
  onAccept,
  onReject
}: CompromiseOptionProps) {
  const [loading, setLoading] = useState(false);
  const [showDetails, setShowDetails] = useState(false);

  const handleAccept = async () => {
    try {
      setLoading(true);

      await apiRequest.post(`/api/disputes/${caseId}/select-option`, {
        optionId: compromiseOption.optionId,
        comments: 'Accepting compromise option generated by AI'
      });

      onAccept();
    } catch (error: any) {
      alert(error.message || 'Failed to accept compromise');
    } finally {
      setLoading(false);
    }
  };

  const handleReject = async () => {
    try {
      setLoading(true);

      await apiRequest.post(`/api/disputes/${caseId}/select-option`, {
        optionId: null,
        rejected: true,
        comments: 'Rejecting compromise option - requesting court forwarding'
      });

      onReject();
    } catch (error: any) {
      alert(error.message || 'Failed to reject compromise');
    } finally {
      setLoading(false);
    }
  };

  const pros = currentUserPartyType === 'complainant' 
    ? compromiseOption.prosForComplainant 
    : compromiseOption.prosForRespondent;

  const cons = currentUserPartyType === 'complainant'
    ? compromiseOption.consForComplainant
    : compromiseOption.consForRespondent;

  return (
    <div className="space-y-6">
      {/* Header Alert */}
      <div className="bg-amber-50 border border-amber-200 rounded-lg p-6">
        <div className="flex items-start gap-4">
          <Scale className="w-8 h-8 text-amber-600 flex-shrink-0" />
          <div className="flex-1">
            <h3 className="text-lg font-semibold text-amber-900 mb-2">
              Compromise Option Generated
            </h3>
            <p className="text-amber-800 text-sm mb-3">
              Since you and the other party selected different options, our AI has generated 
              a balanced compromise solution that considers both perspectives.
            </p>
            <div className="flex items-center gap-4 text-sm">
              <div className="flex items-center gap-2">
                <Users className="w-4 h-4 text-amber-600" />
                <span className="text-amber-700">
                  <strong>Complainant</strong> selected: {complainantSelection.selectedOptionName}
                </span>
              </div>
              <div className="flex items-center gap-2">
                <Users className="w-4 h-4 text-amber-600" />
                <span className="text-amber-700">
                  <strong>Respondent</strong> selected: {respondentSelection.selectedOptionName}
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Compromise Option Card */}
      <div className="bg-gradient-to-br from-purple-50 to-blue-50 border-2 border-purple-300 rounded-xl shadow-lg">
        <div className="p-6">
          {/* Header */}
          <div className="flex items-center justify-between mb-6">
            <div className="flex items-center gap-3">
              <div className="p-3 bg-purple-600 rounded-lg">
                <Lightbulb className="w-6 h-6 text-white" />
              </div>
              <div>
                <h3 className="text-xl font-bold text-gray-900">{compromiseOption.optionName}</h3>
                <p className="text-sm text-gray-600 mt-1">AI-Generated Middle Ground Solution</p>
              </div>
            </div>
            <div className="text-right">
              <div className="flex items-center gap-2 mb-1">
                <Scale className="w-4 h-4 text-purple-600" />
                <span className="text-2xl font-bold text-purple-600">
                  {compromiseOption.fairnessScore}/10
                </span>
              </div>
              <p className="text-xs text-gray-600">Fairness Score</p>
            </div>
          </div>

          {/* Proposed Resolution */}
          <div className="bg-white rounded-lg p-5 mb-4">
            <h4 className="text-sm font-semibold text-gray-700 mb-2">Proposed Resolution</h4>
            <p className="text-gray-800 leading-relaxed">{compromiseOption.proposedResolution}</p>
          </div>

          {/* Legal Basis */}
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-4">
            <h4 className="text-sm font-semibold text-blue-900 mb-2">Legal Basis</h4>
            <p className="text-blue-800 text-sm">{compromiseOption.legalBasis}</p>
          </div>

          {/* Timeline */}
          <div className="flex items-center gap-2 text-sm text-gray-700 mb-4">
            <Calendar className="w-4 h-4" />
            <span>Estimated implementation: <strong>{compromiseOption.timelineDays} days</strong></span>
          </div>

          {/* Show/Hide Details Button */}
          <button
            onClick={() => setShowDetails(!showDetails)}
            className="text-purple-600 hover:text-purple-700 font-medium text-sm mb-4"
          >
            {showDetails ? '▼ Hide detailed analysis' : '▶ Show detailed analysis'}
          </button>

          {/* Detailed Analysis */}
          {showDetails && (
            <div className="space-y-4 mt-4 pt-4 border-t border-purple-200">
              {/* Pros and Cons */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* Pros */}
                <div className="bg-green-50 rounded-lg p-4">
                  <div className="flex items-center gap-2 mb-3">
                    <CheckCircle className="w-5 h-5 text-green-600" />
                    <h4 className="font-semibold text-green-900">Benefits for You</h4>
                  </div>
                  <ul className="space-y-2">
                    {pros.map((pro, index) => (
                      <li key={index} className="flex items-start gap-2 text-sm text-green-800">
                        <span className="text-green-600 mt-0.5">•</span>
                        <span>{pro}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                {/* Cons */}
                <div className="bg-red-50 rounded-lg p-4">
                  <div className="flex items-center gap-2 mb-3">
                    <XCircle className="w-5 h-5 text-red-600" />
                    <h4 className="font-semibold text-red-900">Considerations</h4>
                  </div>
                  <ul className="space-y-2">
                    {cons.map((con, index) => (
                      <li key={index} className="flex items-start gap-2 text-sm text-red-800">
                        <span className="text-red-600 mt-0.5">•</span>
                        <span>{con}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>

              {/* Implementation Steps */}
              <div className="bg-white rounded-lg p-4">
                <div className="flex items-center gap-2 mb-3">
                  <TrendingUp className="w-5 h-5 text-purple-600" />
                  <h4 className="font-semibold text-gray-900">Implementation Steps</h4>
                </div>
                <ol className="space-y-2">
                  {compromiseOption.implementationSteps.map((step, index) => (
                    <li key={index} className="flex items-start gap-3 text-sm text-gray-700">
                      <span className="flex-shrink-0 w-6 h-6 bg-purple-100 text-purple-700 rounded-full flex items-center justify-center text-xs font-semibold">
                        {index + 1}
                      </span>
                      <span className="pt-0.5">{step}</span>
                    </li>
                  ))}
                </ol>
              </div>
            </div>
          )}
        </div>

        {/* Action Buttons */}
        <div className="bg-gray-50 px-6 py-4 rounded-b-xl border-t border-purple-200">
          <div className="flex items-start gap-4">
            <div className="flex-1">
              <div className="flex items-start gap-2 text-sm text-gray-600 mb-3">
                <AlertCircle className="w-4 h-4 flex-shrink-0 mt-0.5" />
                <p>
                  <strong>Important:</strong> If you reject this compromise, the case will be 
                  automatically forwarded to the appropriate court system for judicial resolution.
                </p>
              </div>
            </div>
          </div>
          
          <div className="flex gap-3">
            <button
              onClick={handleReject}
              disabled={loading}
              className="flex-1 px-6 py-3 bg-white border-2 border-red-300 text-red-700 rounded-lg hover:bg-red-50 font-semibold transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {loading ? 'Processing...' : 'Reject & Forward to Court'}
            </button>
            <button
              onClick={handleAccept}
              disabled={loading}
              className="flex-1 px-6 py-3 bg-green-600 text-white rounded-lg hover:bg-green-700 font-semibold transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
            >
              {loading ? (
                'Processing...'
              ) : (
                <>
                  <CheckCircle className="w-5 h-5" />
                  Accept Compromise
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
