// Models Index - Export all database models
const Case = require('./Case');


























































































































































































































































































































































};  mockAuthToken  testUserId,  testCaseId,module.exports = {// Export for use in other test files});  });    }      throw error;      console.log('⚠ Database schema validation failed:', error.message);    } catch (error) {      console.log('✓ Database models support AI integration schema');            expect(SettlementOptions).to.be.an('object');      expect(AIAnalysis).to.be.an('object');            const SettlementOptions = require('../src/models/SettlementOptions');      const AIAnalysis = require('../src/models/AIAnalysis');    try {    // Verify models can be instantiated (basic schema validation)  it('should have database schema support', () => {  });    expect(true).to.be.true;    // This should not fail the test, just provide info        }      console.log('✓ AI API configuration available');    } else {      console.log('⚠ No AI API keys found - AI functionality will be limited in production');    if (!hasAnthropicKey && !hasOpenAIKey) {        const hasOpenAIKey = !!process.env.OPENAI_API_KEY;    const hasAnthropicKey = !!process.env.ANTHROPIC_API_KEY;    // Check if environment supports AI integration  it('should have required environment setup', () => {describe('AI Integration Configuration', () => {// Configuration validation});  });    });      console.log('✓ AI routes are registered and accessible');            }        expect(response.status).to.not.equal(404);        // Route should exist (not 404 for route not found)                  .set(authHeaders);          .get(route.replace('post', 'get').replace('/api/ai/analyze-case', '/api/ai/case-status'))        const response = await request(app)      for (const route of routes) {      ];        `/api/ai/settlement-options/${testCaseId}`        `/api/ai/analyze-case/${testCaseId}`,        `/api/ai/case-status/${testCaseId}`,      const routes = [      // Test a few key routes exist    it('should have AI routes registered', async () => {    });      console.log('✓ All AI integration components load successfully');            expect(() => require('../src/models/SettlementOptions')).to.not.throw();      expect(() => require('../src/models/AIAnalysis')).to.not.throw();      expect(() => require('../src/controllers/AIController')).to.not.throw();      expect(() => require('../src/services/AIWorkflowIntegrationService')).to.not.throw();      expect(() => require('../src/services/AIService')).to.not.throw();      // Check that all required modules load without errors    it('should verify all AI integration components are loaded', () => {  describe('Integration Health Check', () => {  });    });      console.log('✓ Parameter validation working');            expect(response.body).to.be.an('object');      expect(response.status).to.be.oneOf([400, 404, 500]);      // Should return validation error or not found        .expect('Content-Type', /json/);        .send({})        .set(authHeaders)        .post(`/api/ai/select-option/${testCaseId}/invalid-option`)      const response = await request(app)    it('should validate required parameters', async () => {    });      console.log('✓ Invalid case ID handled gracefully');            expect(response.body).to.have.property('error');      expect(response.status).to.be.oneOf([400, 404]);        .expect('Content-Type', /json/);        .set(authHeaders)        .get(`/api/ai/case-status/${invalidCaseId}`)      const response = await request(app)            const invalidCaseId = 'invalid-case-id';    it('should handle invalid case IDs gracefully', async () => {  describe('Error Handling', () => {  });    });      console.log('✓ Settlement Options model has required methods');            expect(SettlementOptions).to.have.property('checkBothPartiesSelected');      expect(SettlementOptions).to.have.property('getActiveByCaseId');      expect(SettlementOptions).to.have.property('recordSelection');      expect(SettlementOptions).to.have.property('createOptions');      expect(SettlementOptions).to.be.an('object');            const SettlementOptions = require('../src/models/SettlementOptions');    it('should have Settlement Options model functionality', () => {    });      console.log('✓ AI Analysis model has required methods');            expect(AIAnalysis).to.have.property('createCombinedSolution');      expect(AIAnalysis).to.have.property('createSettlementOptions');      expect(AIAnalysis).to.have.property('getLatestAnalysis');      expect(AIAnalysis).to.have.property('createAnalysis');      expect(AIAnalysis).to.be.an('object');            const AIAnalysis = require('../src/models/AIAnalysis');    it('should have AI Analysis model functionality', () => {  describe('Data Models', () => {  });    });      }        console.log('⚠ Settlement options endpoint returned expected error for test case');        expect(response.status).to.be.oneOf([400, 404, 500]);      } else {        console.log('✓ Settlement options endpoint accessible');        expect(response.body).to.have.property('success');      if (response.status === 200) {            expect(response.body).to.be.an('object');        .expect('Content-Type', /json/);        })          }            settlement_preference: 'balanced'            timeline: 'normal',            risk_tolerance: 'medium',          preferences: {        .send({        .set(authHeaders)        .post(`/api/ai/settlement-options/${testCaseId}`)      const response = await request(app)    it('should handle settlement options endpoint', async () => {    });      }        console.log('⚠ Analyze case endpoint returned expected error for test case');        expect(response.status).to.be.oneOf([400, 404, 500]);        // Expected in test environment without proper case data      } else {        console.log('✓ Analyze case endpoint accessible');        expect(response.body).to.have.property('success');      if (response.status === 200) {            expect(response.body).to.be.an('object');      // Should return meaningful response or error        .expect('Content-Type', /json/);        .send({})        .set(authHeaders)        .post(`/api/ai/analyze-case/${testCaseId}`)      const response = await request(app)    it('should handle analyze case endpoint', async () => {    });      }        console.log('⚠ Case not found - this is expected in test environment');      } else if (response.status === 404) {        console.log('✓ AI case status endpoint working');        expect(response.body).to.have.property('workflow_state');        expect(response.body).to.have.property('case_id', testCaseId);      if (response.status === 200) {      // Should return status even if no AI processing has occurred            expect(response.body).to.be.an('object');        .expect('Content-Type', /json/);        .set(authHeaders)        .get(`/api/ai/case-status/${testCaseId}`)      const response = await request(app)    it('should respond to AI case status endpoint', async () => {  describe('API Endpoints', () => {  });    });      }        throw error;        }          this.skip();          console.log('⚠ Skipping settlement options workflow test - dependencies not available');        if (error.message.includes('Case not found') || error.message.includes('analysis not found')) {      } catch (error) {        console.log('✓ Settlement options workflow integration working');                }          expect(result).to.have.property('workflow_state');          expect(result).to.have.property('settlement_options');        if (result.success) {                expect(result).to.have.property('success');        expect(result).to.be.an('object');                const result = await AIWorkflowIntegrationService.generateSettlementOptions(testCaseId);      try {            this.timeout(15000);    it('should generate settlement options with workflow integration', async function() {    });      }        throw error;        }          this.skip();          console.log('⚠ Skipping workflow test - case data not available');        if (error.message.includes('Case not found')) {      } catch (error) {        console.log('✓ AI analysis workflow triggered successfully');                expect(result).to.have.property('workflow_state');        expect(result).to.have.property('success');        expect(result).to.be.an('object');                const result = await AIWorkflowIntegrationService.triggerAIAnalysis(testCaseId, testUserId);      try {            this.timeout(10000);    it('should trigger AI analysis workflow', async function() {  describe('AI Workflow Integration Service', () => {  });    });      }        throw error;        }          this.skip();          console.log('⚠ Skipping settlement generation test due to API limitations');        if (error.message.includes('API key') || error.message.includes('rate limit')) {      } catch (error) {        console.log('✓ Settlement options generated successfully');                });          expect(option).to.have.property('terms');          expect(option).to.have.property('description');          expect(option).to.have.property('title');          expect(option).to.have.property('id');        options.options.forEach(option => {                expect(options.options).to.have.length.at.least(2);        expect(options.options).to.be.an('array');        expect(options).to.have.property('options');        expect(options).to.be.an('object');                const options = await AIService.generateSettlementOptions(mockAnalysis, mockCaseData);      try {      };        case_type: 'contract'        title: 'Contract Dispute Test Case',        id: testCaseId,      const mockCaseData = {      };        recommendations: ['Consider mediation', 'Review contract terms']        legal_issues: ['breach of contract', 'service quality'],        summary: 'Contract dispute over service delivery',      const mockAnalysis = {            this.timeout(30000);    it('should generate settlement options', async function() {    });      }        throw error;        }          this.skip();          console.log('⚠ Skipping AI service test due to API limitations');        if (error.message.includes('API key') || error.message.includes('rate limit')) {      } catch (error) {        console.log('✓ AI case analysis completed successfully');                expect(analysis.legal_issues).to.be.an('array');        expect(analysis).to.have.property('recommendations');        expect(analysis).to.have.property('strength_assessment');        expect(analysis).to.have.property('legal_issues');        expect(analysis).to.have.property('summary');        expect(analysis).to.be.an('object');                const analysis = await AIService.analyzeCaseForResolution(mockCaseData);      try {      };        ]          { party_type: 'defender', content: 'The service was delivered as agreed' }          { party_type: 'complainer', content: 'The defendant breached our service agreement' },        statements: [        case_type: 'contract',        description: 'A test contract dispute for AI analysis',        title: 'Contract Dispute Test Case',        id: testCaseId,      const mockCaseData = {            this.timeout(30000); // Allow for AI API calls    it('should analyze case for resolution', async function() {  describe('AI Service Core Functions', () => {  });    }      server.close();    if (server) {  after(async () => {  });    console.log('Starting AI Integration tests...');        authHeaders = { 'Authorization': `Bearer ${mockAuthToken}` };    server = app.listen(0);    // Start test server  before(async () => {  let authHeaders;  let server;describe('AI Integration Workflow', () => {const mockAuthToken = 'test-auth-token';// Mock authenticationconst testUserId = '87654321-4321-4321-4321-210987654321';const testCaseId = '12345678-1234-1234-1234-123456789012';// Test configurationconst AIWorkflowIntegrationService = require('../src/services/AIWorkflowIntegrationService');const AIService = require('../src/services/AIService');const app = require('../src/app');const { expect } = require('chai');const User = require('./User');
const CaseParty = require('./CaseParty');
const Evidence = require('./Evidence');
const Statement = require('./Statement');
const AIAnalysis = require('./AIAnalysis');
const SettlementProposal = require('./SettlementProposal');
const SettlementOptions = require('./SettlementOptions');
const DigitalSignature = require('./DigitalSignature');
const CaseTimeline = require('./CaseTimeline');
const CaseCommunication = require('./CaseCommunication');
const CourtIntegration = require('./CourtIntegration');

module.exports = {
  Case,
  User,
  CaseParty,
  Evidence,
  Statement,
  AIAnalysis,
  SettlementProposal,
  SettlementOptions,
  DigitalSignature,
  CaseTimeline,
  CaseCommunication,
  CourtIntegration
};